name: convert

on:
  schedule:
    - cron: 5 * * * *
  push:
    branches:
      - main

jobs:
  build: 
    environment: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: convert
        run: ./generate.sh
        env:
          SUBSCRIPTION_URL: ${{ secrets.SUBSCRIPTION_URL }}
          GIST_TOKEN: ${{ secrets.GIST_TOKEN }}
          SUBCONVERTER_VERSION: ${{ vars.SUBCONVERTER_VERSION }}
