name: convert

on:
  schedule:
    - cron: 5 * * * *
  push:
    branches:
      - main

jobs:
  build: 
    environment: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - run: npm install -g @bitwarden/cli
      - uses: pnpm/action-setup@v4
        with:
          run_install: true
      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "latest"
      - name: convert
        run: ./main.sh
        env:
          GIST_TOKEN: ${{ secrets.GIST_TOKEN }}
          SUBCONVERTER_VERSION: ${{ vars.SUBCONVERTER_VERSION }}
          GIST_ID: ${{ secrets.GIST_ID }}
          VAULTWARDEN_SERVER_URL: ${{ secrets.VAULTWARDEN_SERVER_URL }}
          API_CLIENT_ID: ${{ secrets.API_CLIENT_ID }}
          API_CLIENT_SECRET: ${{ secrets.API_CLIENT_SECRET }}
          MASTER_PASSWORD: ${{ secrets.MASTER_PASSWORD }}
          PROCESS_SCRIPTS_URL: ${{ secrets.PROCESS_SCRIPTS_URL }}
